config/routes.rb
Rails.application.routes.draw do

  root 'statics#index'

  get 'manual' => 'statics#manual', :as => 'manual'
  get 'ordering' => 'orderings#orderings', :as => 'ordering'
  get 'constants' => 'constants#constants', :as => 'constants'
  get 'queryBuilderOrdering' => 'orderings#queryBuilderOrdering', :as => 'queryBuilderOrdering'
  post '/createByExt' , to: 'constants#createByExt'
  post '/createByTrap' , to: 'constants#createByTrap'
  get 'listarConst' => 'constants#listarConst', :as => 'listarConst'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/constants_controller.rb
class ConstantsController < ApplicationController

	def constants
		# query = "SELECT information_schema_fuzzy.constants2.constant_name,
 				# information_schema_fuzzy.constants2.value
				# FROM information_schema_fuzzy.constants2";
		# @cons = connection.execute(query);
		if session[:created].nil?
			session[:ident] = request.session_options[:id]
			session[:created] = true
		end

		if (flash[:constantsQ] == 'complete')
			@data = @@consts
		else
			@data = {}
		end

	end

	def createByTrap
		name = params[:name]
		x1 = params[:x1]
		x2 = params[:x2]
		x3 = params[:x3]
		x4 = params[:x4]
		connection = ActiveRecord::Base.connection()
		q1 = "INSERT INTO information_schema_fuzzy.constants2 
		(constant_schema, domain_name, constant_name, value, fuzzy_type) 
		VALUES ('NULL', 'fuzzyint','#{name}-#{session[:ident]}',ROW(ARRAY[0.0, 1.0, 1.0, 0.0], 
		ARRAY[#{x1}, #{x2}, #{x3}, #{x4}], '0'), 'NULL')"
		q2 = "SELECT EXISTS 
		(SELECT 1 FROM information_schema_fuzzy.constants2 
			WHERE constant_name = '#{name}-#{session[:ident]}' AND domain_name = 'fuzzyint' 
			AND constant_schema = 'public' LIMIT 1)"
		q3 = "SELECT EXISTS 
		(SELECT 1 FROM information_schema_fuzzy.domains2 WHERE domain_name = 'fuzzyint' LIMIT 1);"
		q4 = "UPDATE information_schema_fuzzy.constants2 
		SET constant_schema = 'public', fuzzy_type = 'fuzzytrapezoid' 
		WHERE constant_schema = 'NULL';"

		begin
			connection.execute(q1)
			connection.execute(q2)
			connection.execute(q3)
			connection.execute(q4)
		rescue
		end
	end

	def createByExt
		name = params[:name]
		val = params[:valor]
		grd = params[:grado]
		array1 = "ARRAY["
		array2 = "ARRAY["

		connection = ActiveRecord::Base.connection()

		val.each do |p|
			if not p.blank?
				array1 = array1 + "#{p},"
			end
		end

		1.times do array1.chop! end

		array1 = array1 + "]"

		grd.each do |p|
			if not p.blank?
				array2 = array2 + "#{p},"
			end
		end

		1.times do array2.chop! end

		array2 = array2 + "]"

		q1 = "INSERT INTO information_schema_fuzzy.constants2 
		(constant_schema, domain_name, constant_name, value, fuzzy_type) 
		VALUES ('NULL', 'fuzzyint','#{name}-#{session[:ident]}',ROW(#{array2},
		#{array1}, '1'), 'NULL')" 
	
		puts q1
		q2 = "SELECT EXISTS 
		(SELECT 1 FROM information_schema_fuzzy.constants2 
			WHERE constant_name = '#{name}-#{session[:ident]}' AND domain_name = 'fuzzyint' 
			AND constant_schema = 'public' LIMIT 1)"
		q3 = "SELECT EXISTS 
		(SELECT 1 FROM information_schema_fuzzy.domains2 WHERE domain_name = 'fuzzyint' LIMIT 1);"
		q4 = "UPDATE information_schema_fuzzy.constants2 
		SET constant_schema = 'public', fuzzy_type = 'fuzzyextension' 
		WHERE constant_schema = 'NULL'"

		begin
			puts '0'
			connection.execute(q1)
			puts "hizo1"
			connection.execute(q2)
			puts '2'
			connection.execute(q3)
			puts '3'
			connection.execute(q4)
			puts '4'
		rescue
		end
	end

	def listarConst
		connection = ActiveRecord::Base.connection()
		q1 = "select constant_name, value from information_schema_fuzzy.constants2 
		where constant_name like '%#{session[:ident]}'"
		@@consts = connection.execute(q1)

		respond_to do |format|
			flash[:constantsQ] = 'complete'
			format.html { redirect_to :action => :constants }
		end
	end

end

app/controllers/orderings_controller.rb
class OrderingsController < ApplicationController

	def orderings
		# query = "SELECT codigo_pokedex_nacional,
		# 		information_schema_fuzzy.fuzzy2_tostring(pokemon.value) AS
		# 		value_human_readable FROM pokemon"
		if (flash[:dataQ] == 'complete')
			@data = @@data
		else
			@data = {}
		end
	end

	def queryBuilderOrdering
		@query = {}
		@query[:select] = "codigo_pokedex_nacional, nombre, poder_base_estimado"
		@query[:order] = params[:order]
		@query[:using] = params[:using]


		connection = ActiveRecord::Base.connection();
		if (@query[:using] == 'CENTROID')
			q1 = "UPDATE information_schema_fuzzy.current_orderings2 SET ordering = 2"
			connection.execute(q1)
		end
		if (@query[:using] == 'CHOQUET')
			q1 = "UPDATE information_schema_fuzzy.current_orderings2 SET ordering = 1"
			connection.execute(q1)
		end

		q2 = "SELECT #{@query[:select]} FROM pokemon ORDER BY poder_base_estimado #{@query[:order]}"
		@@data = connection.execute(q2)

    q3 = "UPDATE information_schema_fuzzy.current_orderings2 SET ordering = 3"
    connection.execute(q3)
	
		respond_to do |format|
			flash[:dataQ] = 'complete'
			flash[:order] = params[:order]
			flash[:using] = params[:using]
			format.html { redirect_to :action => :orderings }
		end

	end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def index
	end
	def manual
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constants_helper.rb
module ConstantsHelper
end

app/helpers/orderings_helper.rb
module OrderingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/constants/_form.html.erb
<%= text_field_tag :v1, nil, {:class =>"form-control by-extension-element", :placeholder => "v", :onchange => "changeByExtension(1)"}%>
<%= text_field_tag :g1, nil, {:class =>"form-control by-extension-element", :placeholder => "g", :onchange => "changeByExtension(1)"}%>
<button type="button" class="btn btn-default btn-xs" style="width: 40px;" onclick="removeByExtension('1')">

app/views/constants/constants.html.erb
<!DOCTYPE html>

	<%= javascript_include_tag 'fuzzy.js' %>
	<%= javascript_include_tag 'google-charts.js' %>	

<div class="content">
	<h1>Constantes</h1>
	<p>
		Aquí podrás crear constantes difusas!
	</p>
	<div style="margin-top: 20px;">
		<table style="margin: auto;">
			<tbody>
				<tr>
					<td style="padding: 15px 15px 15px 15px;">
						<label style="margin: auto;">
							Nombre:
						</label>
					</td>
					<td style="padding: 15px 15px 15px 15px;" colspan="2">
						<input class="form-control" id="name" name="name" style="width: 100%;" type="text">
					</td>
				</tr>
				<tr>
					<td style="padding: 0 15px 0 15px;">
						<strong>Tipo:</strong>
					</td>
					<td style="padding: 0 15px 0 15px;">
						<input type="radio" name="optionsRadios" id="optionsRadios1" value="trapezoide" onclick="trapezoid()" checked>
						Trapezoidal
					</td>
					<td style="padding: 0 15px 0 15px;">
						<input type="radio" name="optionsRadios" id="optionsRadios1" value="extension" onclick="byExtension()">
						Por extensión
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="trapezoid">
		<div style="width: 100%; height: 60px;">
			<form class="form-group" role="form">
				<div class="col-xs-2" style="width: 100%;">
					<table style="margin: auto; margin-bottom: 30px;">
						<tbody>
							<tr>
								<td>
									<input class="form-control trapezoid-element" id="x1" name="x1" onchange="changeTrapezoid(0)" placeholder="x1" type="text">
								</td>
								<td>
									<input class="form-control trapezoid-element" id="x2" name="x2" onchange="changeTrapezoid(1)" placeholder="x2" type="text">
								</td>
								<td>
									<input class="form-control trapezoid-element" id="x3" name="x3" onchange="changeTrapezoid(2)" placeholder="x3" type="text">
								</td>
								<td>
									<input class="form-control trapezoid-element" id="x4" name="x4" onchange="changeTrapezoid(3)" placeholder="x4" type="text">
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</form>
		</div>
<%= javascript_tag do %>
		google.load("visualization", "1", {packages:["corechart"]});
		google.setOnLoadCallback(draw_trapezoid);
		function draw_trapezoid() {
			var data = google.visualization.arrayToDataTable(trapezoid_images);

			var options = {
				'width':400,
				'height':80,
				'legend': 'none',
				'margin': 'auto',
				hAxis: { ticks: trapezoid_ticks}
			};

			var chart = new google.visualization.LineChart(document.getElementById('grafico-trapecio'));

			chart.draw(data, options);
		}
<% end %>
		<div id="grafico-trapecio" style="margin-left: 200px; margin-right:200px;"></div>
	</div>
	<div id="by-extension" style="display: none;">
		<form class="form-group" role="form">
			<div class="col-xs-2" style="width: 100%; padding-left: 0px;">
				<table id="extension-elements">
					<tbody>
						<tr>
							<td style="padding-bottom: 20px;">
								<p>
									<strong>valor:</strong>
								</p>
								<p>
									<strong>grado:</strong>
								</p>
							</td>
							<td id="extension_1">
								<input type="text" class="form-control by-extension-element" placeholder="v" id="v1" onchange="changeByExtension(1)">
								<input type="text" class="form-control by-extension-element" placeholder="g" id="p1" onchange="changeByExtension(1)">
								<button type="button" class="btn btn-default btn-xs" style="width: 40px;" onclick="removeByExtension('1')">
									<span class="glyphicon glyphicon-trash"></span>
								</button>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</form>
		<table style="margin:auto; margin-bottom: 30px;">
			<tbody>
				<tr>
					<td>
						Agrega otro punto
						<button type="button" class="btn btn-success btn-xs" onclick="addByExtension()">
							<span class="glyphicon glyphicon-plus white"></span>
						</button>
					</td>
				</tr>
			</tbody>
		</table>
<%= javascript_tag do %>
		google.load("visualization", "1", {packages:["corechart"]});
		google.setOnLoadCallback(draw_extension);

		function draw_extension() {
			var data = google.visualization.arrayToDataTable(extension_images);
			var options = {
				legend: 'none',
				hAxis: {ticks: extension_ticks}
			};

			var chart = new google.visualization.ScatterChart(document.getElementById('grafico-extension'));

			chart.draw(data, options);
		}
<% end %>
		<div id="grafico-extension" style="margin-left: 200px; margin-right:200px;"></div>
	</div>
	<table style="margin:auto;">
		<tbody>
			<tr>
				<td style="padding: 5px;">
					
					<button type="button" id='bt1' class="btn btn-info" onclick = sentByTrap()>
						Crear constante
					</button>
				</td>
				<td style="padding: 5px;">
					<!-- <button type="button" class="btn btn-primary">
						Listar constantes
					</button> -->
					<%= button_to "Listar Constantes", {:controller => :constants, :action => :listarConst}, :class => "btn btn-primary", :method => :get %>
				</td>
			</tr>
		</tbody>
	</table>

	<% if flash[:constantsQ] == 'complete' %>
		<table class="table table-hover">                         
			<thead>		
				<tr>                          
					<th>Nombre</th>
					<th>Valor</th>
				</tr>
			</thead>
			<tbody>				
				<% @data.each do |row| %>
				<tr>
					<td><%= row.fetch("constant_name").sub!("-#{session[:ident]}","") %></td>
					<td><%= row.fetch("value") %></td>
				</tr>
				<% end %> 
			</tbody>		
		</table>  
	<%end%>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>fuzzydoDB - Tipo 2</title>
	<meta charset="UTF-8">
	<%= stylesheet_link_tag 'bootstrap.css' %>
	<%= stylesheet_link_tag 'style.css' %>
	<%= javascript_include_tag 'fuzzy.js' %>
	<%= javascript_include_tag 'jquery-2.1.1.min.js' %>
	<%= javascript_include_tag 'google-charts.js' %>	
	<%= csrf_meta_tag %>
</head>





<body>
	<div class="blue-band"></div>
	<div class="header">
		<div class="brand">
			<%= image_tag("logo_mascota.png", height: "70") %>
		</div>
		<div class="menu">
			<ul>
				<li><%= link_to "fuzzydoDB", root_path %></li>				  
				<li><%= link_to "Manual", manual_path %></li>
				<li><%= link_to ordering_path do %>
					Ordenamientos
					<span class="label label-warning">New</span>
					<% end %>
				</li>
				<li><%= link_to constants_path do %>
					Constantes
					<span class="label label-warning">New</span>
					<% end %>
				</li>
			</ul>
		</div>
	</div>


	<%= yield %>


	<footer>
		<table align="center">
			<tr>
				<td align="center" style="padding-bottom: 10px;">
					<%= image_tag("cebolla.gif", height: "40") %>			
				</td>
				<td style="padding-left: 10px;">
					<p>
						<strong>FuzzyDB</strong> <br>
						Desarrollo de la extensión de datos difusos Tipo II <br>
						Proyecto desarrollado por: Stephanie Alibrandi, José Delgado y José Figueredo.
					</p>
				</td>
			</tr>
		</table>
	</footer>

</body>
</html>

app/views/orderings/orderings.html.erb
<!DOCTYPE html>
<div class="content">
	<h1>Ordenamientos</h1>
	<h2> Ejecutando el ordenamiento </h2>
	<p>
		En esta sección podrás ejecutar los diferentes ordenamientos existentes en FuzzyDB: el ordenamiento basado en la
		<strong>Integral de Sugeno</strong>, el ordenamiento basado en la <strong>integral de Choquet</strong> y el ordenamiento basado en 
		el <strong>Centroide y la integral de Riemman</strong>.
		Sencillamente selecciona según cuál ordenamiento deseas ordenar!
	</p>
	<div class="panel panel-default" style="margin-left: 25px; margin-right: 25px;">
		<div class="panel-body">
			<%= form_tag(queryBuilderOrdering_path, method:"get", multipart: true, :class => "form-inline") do %>
				<p class="console">
					SELECT codigo_pokedex_nacional, nombre, poder
					<!-- < % = select_tag(:select , options_for_select({"Codigo Pokedex Nacional" => "codigo_pokedex_nacional", "codigo_pokedex_nacional" => "codigo_pokedex_nacional"}), { :class => "form-control"}) %> -->
				</p>
				<p class="console">
					FROM pokemon 
				</p> 
				<p class="console">
					ORDER BY poder 
					<%= select_tag(:order , options_for_select({"ASC" => "ASC", "DESC" => "DESC"}), { :class => "form-control"}) %>
					USING
					<%= select_tag(:using , options_for_select({"SUGENO" => "SUGENO", "CHOQUET" => "CHOQUET", "CENTROID" => "CENTROID"}), { :class => "form-control"}) %>

					<%= submit_tag("Ejecutar Consulta", {:class => "btn btn-success"}) %>
				</p>
			<%end%>

		</div>
	</div>

	<% if flash[:dataQ] == 'complete' %>
		<table class="table table-hover">                         
			<h2> Resultados - Order By: <%= flash[:order] %> - Using: <%= flash[:using]%> </h2>
			<thead>		
				<tr>                          
					<th>Codigo Pokedex</th>
					<th>Nombre</th>
					<th>Poder Base Estimado</th>
				</tr>
			</thead>
			<tbody>				
				<% @data.each do |row| %>
				<tr>
					<td><%= row.fetch("codigo_pokedex_nacional") %></td>
					<td><%= row.fetch("nombre") %></td>
					<td><%= row.fetch("poder_base_estimado") %></td>
				</tr>
				<% end %> 
			</tbody>		
		</table>  
	<%end%>
</div>

app/views/statics/index.html.erb
<!DOCTYPE html>
<div class="blue-band"></div>
<div class="content">
	<%= image_tag("fuzzydoDB.png", height: "70") %>
	<h2>Implementación de Datos Difusos Tipo II</h2>

	<h4>En esta aplicación web podrás probar ordenamientos de datos difusos tipo II,
		crear constantes y realizar consultas a la base de datos. Si eres nuevo acá,
		te recomendamos leer la sección <i>Manual</i> antes de empezar.
		<b>¡Bienvenido!</b>
	</h4>

</div>

app/views/statics/manual.html.erb
<!DOCTYPE html>
<div class="blue-band"></div>
<div class="content">
	<h1>Manual de usuario</h1>
	<h3>Creación del dominio</h3>
	<p> 
		Antes que nada es importante especificar el dominio sobre el cual se manejarán
		los datos difusos de Tipo II. La instrucción para crear el dominio es la siguiente.
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				CREATE FUZZY DOMAIN 'dominio' <br>
				AS POSSIBILITY DISTRIBUTION ON INTEGER;
			</p>
		</div>
	</div>
	<h3>Inserción de datos</h3>
	<p>
		Una vez que el dominio está creado, se pueden crear tablas que utilicen estos
		nuevos atributos, como por ejemplo:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				CREATE TABLE 'tabla'( <br>
				&nbsp;&nbsp;&nbsp;att_1 type, <br>
				&nbsp;&nbsp;&nbsp;...<br>
				&nbsp;&nbsp;&nbsp;fuzzy_att 'dominio'<br>
				);
			</p>
		</div>
	</div>
	<p>
		Y se pueden insertar elementos difusos en estas tablas: números difusos
		por extensión o trapezoidales, como por ejemplo:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				INSERT INTO 'tabla' ('fuzzy_att') VALUES ({f 0.5/1, 1.0/2, 0.8/3, 0.5/4});<br>
				INSERT INTO 'tabla' ('fuzzy_att') VALUES ({f (1, 9, 11, 13)});
			</p>
		</div>
	</div>
	<h3>Consulta de datos</h3>
	<p>
		Los datos en FuzzyDB puede consultarse con normalidad por ejempo ejecutando
		esta simple sentencia SELECT:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				SELECT 'atributos' <br>
				FROM 'tabla' <br>
				WNERE 'condiciones';
			</p>
		</div>
	</div>
	<h4>Ordenamiento de datos <span class="label label-warning">New</span> </h4>
	<p>
		Ahora se puede decidir por cuál ordenamiento se desea ordenar. Existen tres ordenamientos: 
		el que se basa en la integral de Sugeno cuya sintaxis es:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				SELECT 'atributos' <br>
				FROM 'tabla' <br>
				WNERE 'condiciones' <br>
				ORDER BY 'fuzzy_att' USING SUGENO;
			</p>
		</div>
	</div>
	<p>
		el que se basa en la integral de Choquet cuya sintaxis es:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				SELECT 'atributos' <br>
				FROM 'tabla' <br>
				WNERE 'condiciones' <br>
				ORDER BY 'fuzzy_att' USING CHOQUET;
			</p>
		</div>
	</div>
	<p>
		y el que se basa en el centroide y en la integral de Riemman cuya sintaxis es:
	</p>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				SELECT 'atributos' <br>
				FROM 'tabla' <br>
				WNERE 'condiciones' <br>
				ORDER BY 'fuzzy_att' USING CENTROID;
			</p>
		</div>
	</div>
	<h3>Constantes <span class="label label-warning">New</span></h3>
	<p>
		También permitimos la creación de constantes de Tipo II en donde, en lugar de
		insertar varias veces el número difuso, se puede definir una constante e insertar
		la constante.
	</p>
	<h4>Creación de constantes</h4>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				CREATE FUZZY CONSTANT 'constante' 'dominio' := {f (50, 55, 60, 65)};
			</p>
		</div>
	</div>
	<h4>Inserción</h4>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				INSERT INTO 'tabla' ('fuzzy_att') VALUES ('constante');
			</p>
		</div>
	</div>
	<h4>Actualización</h4>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				UPDATE 'tabla' <br> 
				SET 'fuzzy_att' = 'constante'<br> 
				WHERE 'condiciones';
			</p>
		</div>
	</div>
	<h4>Aliasing</h4>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				CREATE FUZZY CONSTANT 'constante2' 'dominio' := 'constante';
			</p>
		</div>
	</div>
	<h4>Consulta de datos</h4>
	<div class="panel panel-default">
		<div class="panel-body">
			<p class="console small">
				SELECT 'atributos' <br>
				FROM 'tabla' <br>
				WNERE 'fuzzy_at' [>, >=, <>, <=, <] 'constante';
			</p>
		</div>
	</div>
</div>

app/views/temp/consola.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
		<link rel="stylesheet" type="text/css" href="css/style.css"/>

		<script type="text/javascript" src="js/fuzzy.js"></script>
		<script src="js/jquery-2.1.1.min.js"></script>
	</head>
	<body>

		<div class="header">
			<div class="brand">
				<img src="img/logo_mascota.png" height="70px">
			</div>
			<div class="menu">
				<ul>
				  <li><a href="home.html">FuzzyDB</a></li>
				  <li><a href="manual.html">Manual</a></li>
				  <li>
				  	<a href="ordenamientos.html">
				  		<span> Ordenamientos<span> 
				  		<span class="label label-warning">New</span>
				  	</a>
				  </li> 
				  <li>
				  	<a href="consola.html">
				  		<span> Constantes<span> 
				  		<span class="label label-warning">New</span>
				  	</a>
				  </li>
				</ul>
			</div>
		</div>
		<div class="blue-band"></div>
		<div class="content">
			<h1>Constantes</h1>
			<p>
				Aquí podrás crear constantes difusas!
			</p>
			<div style="margin-top: 20px;">
				<table style="margin: auto;">
					<tbody>
						<tr>
							<td style="padding: 0 15px 0 15px;">
								<label>
							    	<input type="radio" name="optionsRadios" id="optionsRadios1" value="trapezoide" onclick="trapezoid()" checked>
							    	Trapezoidal
							  	</label>
							</td>
							<td style="padding: 0 15px 0 15px;">
								<label>
							    	<input type="radio" name="optionsRadios" id="optionsRadios1" value="extension" onclick="byExtension()">
							    	Por extensión
							  	</label>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div id="trapezoid">
				<form class="form-group" role="form">
	  				<div class="col-xs-2" style="width: 100%;">
						<table style="margin: auto; margin-bottom: 30px;">
							<tbody>
								<tr>
									<td>
		    							<input type="text" class="form-control trapezoid-element" placeholder="x1">
									</td>
									<td>
		    							<input type="text" class="form-control trapezoid-element" placeholder="x2">
									</td>
									<td>
		    							<input type="text" class="form-control trapezoid-element" placeholder="x3">
									</td>
									<td>
		    							<input type="text" class="form-control trapezoid-element" placeholder="x4">
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</form>
			</div>
			<div id="by-extension" style="display: none;">
				<form class="form-group" role="form">
					<div class="col-xs-2" style="width: 100%;">
						<table id="extension-elements">
							<tbody>
								<tr>
									<td id="extension_1">
		    							<input type="text" class="form-control by-extension-element" placeholder="x">
		    							<input type="text" class="form-control by-extension-element" placeholder="y">
		    							<button type="button" class="btn btn-default btn-xs" style="width: 40px;" onclick="removeByExtension('1')">
											<span class="glyphicon glyphicon-trash"></span>
										</button>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</form>
				<table style="margin:auto; margin-bottom: 30px;">
					<tbody>
						<tr>
							<td>
								Agrega otro punto
								<button type="button" class="btn btn-success btn-xs" onclick="addByExtension()">
									<span class="glyphicon glyphicon-plus white"></span>
								</button>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<table style="margin:auto;">
				<tbody>
					<tr>
						<td style="padding: 5px;">
							<button type="button" class="btn btn-info">
								Crear constante
							</button>
						</td>
						<td style="padding: 5px;">
							<button type="button" class="btn btn-primary">
								Listar constantes
							</button>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<footer>
			<table align="center">
				<tr>
					<td align="center" style="padding-bottom: 10px;">
						<img src="img/cebolla.gif" height="40px;">
					</td>
					<td style="padding-left: 10px;">
						<p>
							<strong>FuzzyDB</strong> <br>
							Desarrollo de la extensión de datos difusos Tipo II <br>
							Proyecto desarrollado por: Stephanie Alibrandi, José Delgado y José Figueredo.
						</p>
					</td>
				</tr>
			</table>
		</footer>
	</body>
</html>